### ISSUE TITLE
Diagram should describe the architecture of the server

### ISSUE THREAD

**Issue by konstantin-baranovskiy-alnicko** [Goltzishpt/ota_server#2]
The [diagram](https://github.com/Goltzishpt/ota_server/blob/main/ota_server.png) is not detailed enough.
This diagram should show the internal structure of the server and external connections.
To make the diagram editable for the future modification it is useful to use [PlantUML](https://plantuml.com/class-diagram) format instead of png (PyCharm has a good plugin for PlantUML).

**Comment by Goltzishpt** [comment]
Added planetuml

**Comment by Goltzishpt** [comment]
added plantuml
